name: regulamentos-anac-tags

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install requests
    - name: Run a Python script
      run: |
        python ./regulamentos-anac-tags.py
    - name: Upload JSON file
      uses: actions/upload-artifact@v3
      with:
        name: regulamentos-anac-tags.json
        path: ./regulamentos-anac-tags.json
